version: '3.8'

services:
  skak:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    container_name: skak
    restart: unless-stopped
    ports:
      - "3002:80"
    networks:
      - default

networks:
  default:
    external: false


